### ISSUE TITLE
Detect dynamically added elements

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/locator#16]
You might be able to detect dynamically added custom elements using https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver

I'm not sure how deep it goes, but at least you can do some basic detection. 

Perhaps MutationObserver fires a bit too frequently, you could still batch it to collect only once every X seconds but use the observer as a trigger to know that something actually changed.

**Comment by thepassle** [comment]
fixed in https://github.com/open-wc/locator/pull/26

release will probably be in a week or so
