### ISSUE TITLE
sharing "private" urls

### ISSUE THREAD

**Issue by simi** [open-wc/locator#24]
- as noted at slack

Should data from similar URLs be shared as well?

![image-2](https://user-images.githubusercontent.com/193936/93234460-9c639a00-f77c-11ea-939a-93c0bdef88b1.png)

**Comment by thepassle** [comment]
Currently `127.0.0.1` and `localhost` are added to a `denyList`, should we add more checks here? 🤔

**Comment by simi** [comment]
Seems enough for now. Would it be possible to delete those entries already ingested matching this denyList?

**Comment by thepassle** [comment]
Yep, already deleted them :)

Will close this for now then, thanks again for reporting!
