### ISSUE TITLE
Only store links that are publicly available

### ISSUE THREAD

**Issue by thepassle** [open-wc/locator#25]
More info: https://github.com/open-wc/wild/issues/10

**Comment by marcelorl** [comment]
I'm picking this one.

**Comment by jlengrand** [comment]
Cool, though I wonder if this is not something that should be done on server side @thepassle ? 
How would you go about solving that locally via the extension?

**Comment by jlengrand** [comment]
Ha, reading again it seems like it's doable since it does interact with the server. Have fun @marcelorl !

**Comment by thepassle** [comment]
This indeed already got solved on the API side of things, and I forgot to close this issue because the API is in a different repo 🙁 Im sorry about that @marcelorl 

If you're still interested, there are some other easy-to-get-started with issues however, like this one: https://github.com/open-wc/locator/issues/31
