### ISSUE TITLE
Click Area and on/off for settings is "strange"

### ISSUE THREAD

**Issue by daKmoR** [open-wc/locator#28]
hey,

so with the toggles currently I am not sure what it on and what is off? is left on or off?

also the click area seems off 😅

![LocatorClickArea](https://user-images.githubusercontent.com/24378/93771713-2ba9fb00-fc1e-11ea-9cff-8560c025e80e.gif)

v1.6.0

**Comment by thepassle** [comment]
🤔 Thats weird, im not seeing this behavior:
![toggle](https://user-images.githubusercontent.com/17054057/93772097-b5f25f00-fc1e-11ea-8130-d02bd817a179.gif)

The label and the switch itself should be clickable

Could you try to see if you get the same click behavior here? https://genericcomponents.netlify.app/generic-switch/demo/index.html

**Comment by jlengrand** [comment]
Isn't left like universally off? Can you name one UI where left means "enabled"? I'm not a frontender, genuinely curious. To me it's like traffic lights, even without the color you know green is below? 

What would you add, colors?

**Comment by jlengrand** [comment]
Tested again, i can't reproduce. What browser version are you using?

**Comment by trystan2k** [comment]
Hi, 

I could not reproduce the issue too but I agree with Thomas about the difficulty to identify if it is on or off. I have added a different track background color to better identify (visually) its state.

![locator](https://user-images.githubusercontent.com/447294/95022340-f74f2980-0676-11eb-9d49-6c32c99dc35e.gif)

I also added a `user-select:none` to avoid text to be selected when double-clicking on the label

**Comment by trystan2k** [comment]
@daKmoR I see you tested in v1.6.0 and the latest version is v1.9.0. Maybe this could be already fixed ? Otherwise, could you please share which browser version are you using ? Thanks !

**Comment by daKmoR** [comment]
1.6.0 is the latest release in the web store right?
https://chrome.google.com/webstore/detail/custom-elements-locator/eccplgjbdhhakefbjfibfhocbmjpkafc?hl=en-GB

but yeah I can give it a try and install the current master locally (probably tomorrow 🤗)

**Comment by trystan2k** [comment]
> 1.6.0 is the latest release in the web store right?
> https://chrome.google.com/webstore/detail/custom-elements-locator/eccplgjbdhhakefbjfibfhocbmjpkafc?hl=en-GB
> 
> but yeah I can give it a try and install the current master locally (probably tomorrow 🤗)

Yep, you are right. But I just tested with 1.6.0 and is still working. (Chrome Stable 85.0.4183.121).

**Comment by jlengrand** [comment]
LGTM. @thepassle ?
