### ISSUE TITLE
It'd be great to have a different icon color / shade in case the extension has found web components

### ISSUE THREAD

**Issue by jlengrand** [open-wc/locator#6]
That'd help notice without having to click.

**Comment by jlengrand** [comment]
Well someone smarter thought about it already ! Closed by https://github.com/open-wc/locator/pull/4

**Comment by jlengrand** [comment]
I think this can be closed?

**Comment by jlengrand** [comment]
Just checked, it works. Closing

**Comment by thepassle** [comment]
Thanks to @jorgecasar 🙂

**Comment by jlengrand** [comment]
Yes, much <3
